on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Publish

jobs:
  publish:
    name: Upload to PyPI
    environment: ReleasePlease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: abatilo/actions-poetry@v2
      - name: build
        run: poetry build
      - name: publish
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
