name: "TESTS: Scheduled"
on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  test-latest:
    environment: Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup Test Environment and Run Tox
        uses: ./.github/actions/invoke-tox
        with:
          tox-environment: latest
          install-graphviz: true

  test-pre-release:
    environment: Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup Test Environment and Run Tox
        uses: ./.github/actions/invoke-tox
        with:
          tox-environment: pre-release
          install-graphviz: true

  security-scan:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        scan: ["lib", "dev"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup Test Environment and Run Tox
        uses: ./.github/actions/invoke-tox
        with:
          tox-environment: security-scan-${{ matrix.scan }}
          install-graphviz: true
